### ISSUE TITLE
Skipped tests should not show as fails

### ISSUE THREAD

**Issue by DinisCruz** [gleb-sevruk/pycrunch-engine#12] opened 2020-03-01 14:57 UTC
When using the @skip attribute on a test, it shows as failure

![image](https://user-images.githubusercontent.com/656739/75627973-ced8eb80-5bcc-11ea-9ac6-7ee58615f74e.png)

Here is with that attribute commented

![image](https://user-images.githubusercontent.com/656739/75627979-de583480-5bcc-11ea-95b7-a5931b3c3694.png)

(btw great tool, using it everyday now)

**Comment by gleb-britecore** [comment] 2020-03-01 21:15
Hello, thank you for the report. I'll be able to investigate the issue in the following days.
In the meantime, I believe the issue is somewhere in
pycrunch/plugins/pytest_support/interception_plugin.py
![image](https://user-images.githubusercontent.com/29545691/75633922-e1294880-5c11-11ea-99ce-7b7e4ee053c2.png)

If this causes a big pain you may try adjusting code there until I can come up with a meaningful fix. 
I usually end up changing test name to `def not_a_test_*` instead of using @skip / @ignore attribute

**Comment by gleb-britecore** [comment] 2020-03-05 12:13
For future references:

I found an anomaly in pytest reporter:
For the code
![image](https://user-images.githubusercontent.com/29545691/75980423-19b77380-5eeb-11ea-8d01-10a5a4579f87.png)
It stills shows success:
![image](https://user-images.githubusercontent.com/29545691/75980405-0efcde80-5eeb-11ea-82e1-a37635b06628.png)

But if I use attribute like `@skip('reason')` `report.outcome` will be equal to `skipped`

Anyway I successfully reproduced and fixed the issue and will be updating the package today

**Comment by gleb-britecore** [comment] 2020-03-05 12:39
The issue should be fixed in 0.9.1

pip install --upgrade pycrunch-engine

@DinisCruz Please let me know if it works for you.

**Closed** 2020-08-02 18:31 UTC
